[install]
registry = "https://registry.npmmirror.com/"
scope = "*"

[install."@types"]
registry = "https://registry.npmmirror.com/"

[install."@vscode"]
registry = "https://registry.npmmirror.com/"

[install.vsce]
registry = "https://registry.npmmirror.com/"

[install.ovsx]
registry = "https://registry.npmmirror.com/"
